apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-10T11:10:54Z"
  generateName: alertmanager-prometheus-stack-kube-prom-alertmanager-
  labels:
    alertmanager: prometheus-stack-kube-prom-alertmanager
    app: alertmanager
    app.kubernetes.io/instance: prometheus-stack-kube-prom-alertmanager
    app.kubernetes.io/managed-by: prometheus-operator
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.21.0
    controller-revision-hash: alertmanager-prometheus-stack-kube-prom-alertmanager-6cd7fbf7cc
    statefulset.kubernetes.io/pod-name: alertmanager-prometheus-stack-kube-prom-alertmanager-0
  name: alertmanager-prometheus-stack-kube-prom-alertmanager-0
  namespace: production
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: alertmanager-prometheus-stack-kube-prom-alertmanager
    uid: bec38f3e-242c-44df-ab6f-7106aec7bf3b
  resourceVersion: "583506"
  uid: 7e000ec6-7718-43ac-ac0a-42cdb35aa9b9
spec:
  containers:
  - args:
    - --config.file=/etc/alertmanager/config/alertmanager.yaml
    - --storage.path=/alertmanager
    - --data.retention=120h
    - --cluster.listen-address=
    - --web.listen-address=:9093
    - --web.external-url=http://prometheus-stack-kube-prom-alertmanager.production:9093
    - --web.route-prefix=/
    - --cluster.peer=alertmanager-prometheus-stack-kube-prom-alertmanager-0.alertmanager-operated:9094
    - --cluster.reconnect-timeout=5m
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: quay.io/prometheus/alertmanager:v0.21.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 10
      httpGet:
        path: /-/healthy
        port: web
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 3
    name: alertmanager
    ports:
    - containerPort: 9093
      name: web
      protocol: TCP
    - containerPort: 9094
      name: mesh-tcp
      protocol: TCP
    - containerPort: 9094
      name: mesh-udp
      protocol: UDP
    readinessProbe:
      failureThreshold: 10
      httpGet:
        path: /-/ready
        port: web
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      requests:
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /etc/alertmanager/config
      name: config-volume
    - mountPath: /etc/alertmanager/certs
      name: tls-assets
      readOnly: true
    - mountPath: /alertmanager
      name: alertmanager-prometheus-stack-kube-prom-alertmanager-db
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-twbq2
      readOnly: true
  - args:
    - --listen-address=:8080
    - --reload-url=http://127.0.0.1:9093/-/reload
    - --watched-dir=/etc/alertmanager/config
    command:
    - /bin/prometheus-config-reloader
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: SHARD
      value: "-1"
    image: quay.io/prometheus-operator/prometheus-config-reloader:v0.47.0
    imagePullPolicy: IfNotPresent
    name: config-reloader
    ports:
    - containerPort: 8080
      name: reloader-web
      protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /etc/alertmanager/config
      name: config-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-twbq2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: alertmanager-prometheus-stack-kube-prom-alertmanager-0
  nodeName: centos81.localdomain
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccount: prometheus-stack-kube-prom-alertmanager
  serviceAccountName: prometheus-stack-kube-prom-alertmanager
  subdomain: alertmanager-operated
  terminationGracePeriodSeconds: 120
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: config-volume
    secret:
      defaultMode: 420
      secretName: alertmanager-prometheus-stack-kube-prom-alertmanager-generated
  - name: tls-assets
    secret:
      defaultMode: 420
      secretName: alertmanager-prometheus-stack-kube-prom-alertmanager-tls-assets
  - emptyDir: {}
    name: alertmanager-prometheus-stack-kube-prom-alertmanager-db
  - name: kube-api-access-twbq2
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-05-10T11:10:54Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-05-15T08:13:34Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-05-15T08:13:34Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-05-10T11:10:54Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f5000770a3f14db58efdf5363eed3f1037e334e861422faac529690cb2d9dd52
    image: quay.io/prometheus/alertmanager:v0.21.0
    imageID: docker-pullable://quay.io/prometheus/alertmanager@sha256:24a5204b418e8fa0214cfb628486749003b039c279c56b5bddb5b10cd100d926
    lastState:
      terminated:
        containerID: docker://51600273b9b1fd2cb9320184d3815ba977d22a78dc21522fb8dc8aca39692eb1
        exitCode: 0
        finishedAt: "2021-05-14T05:13:54Z"
        reason: Completed
        startedAt: "2021-05-13T14:53:05Z"
    name: alertmanager
    ready: true
    restartCount: 3
    started: true
    state:
      running:
        startedAt: "2021-05-15T08:13:30Z"
  - containerID: docker://d9a9cb5316c3c6dac229ef1b36cb983655e5c52d5e4241ee3331c54bb483fde6
    image: quay.io/prometheus-operator/prometheus-config-reloader:v0.47.0
    imageID: docker-pullable://quay.io/prometheus-operator/prometheus-config-reloader@sha256:0029252e7cf8cf38fc58795928d4e1c746b9e609432a2ee5417a9cab4633b864
    lastState:
      terminated:
        containerID: docker://04af8e292d1a26ce189d37eb5bfc70065f4dd3f35b1193f698822249299be477
        exitCode: 2
        finishedAt: "2021-05-14T05:13:54Z"
        message: |
          level=info ts=2021-05-13T14:53:05.843740927Z caller=main.go:147 msg="Starting prometheus-config-reloader" version="(version=0.47.0, branch=refs/tags/pkg/client/v0.47.0, revision=539108b043e9ecc53c4e044083651e2ebfbd3492)"
          level=info ts=2021-05-13T14:53:05.843785944Z caller=main.go:148 build_context="(go=go1.16.3, user=simonpasquier, date=20210413-15:46:43)"
          level=info ts=2021-05-13T14:53:05.843963585Z caller=main.go:182 msg="Starting web server for metrics" listen=:8080
          level=info ts=2021-05-13T14:53:05.844143711Z caller=reloader.go:214 msg="started watching config file and directories for changes" cfg= out= dirs=/etc/alertmanager/config
          level=info ts=2021-05-13T14:53:10.328343272Z caller=reloader.go:347 msg="Reload triggered" cfg_in= cfg_out= watched_dirs=/etc/alertmanager/config
        reason: Error
        startedAt: "2021-05-13T14:53:05Z"
    name: config-reloader
    ready: true
    restartCount: 3
    started: true
    state:
      running:
        startedAt: "2021-05-15T08:13:31Z"
  hostIP: 192.168.1.140
  phase: Running
  podIP: 10.40.0.5
  podIPs:
  - ip: 10.40.0.5
  qosClass: Burstable
  startTime: "2021-05-10T11:10:54Z"
