apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx12
  name: nginx12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx12
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx12
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
