apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: deployment
  name: deployment
spec:
  containers:
  - args:
    - nginx
    - replicas=4
    image: nginx
    name: deployment
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
