 apiVersion: v1
 kind: Pod
 metadata:
    name: frontend
 spec:
   containers:
   - name: app
     image: images.my-company.example/app:v4
     resources:
      requests:
         memory: "20Mi"
         cpu:  ".1"
      limits:
         memory: "40Mi"
         cpu: "1"
