apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx_svc
  name: nginx_svc
spec:
  ports:
  - name: 80-80
    nodePort: 30010
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx_svc
  type: NodePort
status:
  loadBalancer: {}
